# Generated by Django 3.0.2 on 2020-01-29 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Jhoice',
        ),
    ]
