# Generated by Django 3.0.2 on 2020-01-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200129_1724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jhoice',
            new_name='Choice',
        ),
    ]
